"use client";

import { useState } from "react";
import { X } from "lucide-react";

type PackageRecord = { id: string; name: string; description: string; basePrice: number; duration: string; inclusions: string; notes: string; active: boolean; };

export function PackageEditForm({ initial, onClose, onSave }: { initial: PackageRecord; onClose: () => void; onSave: (item: PackageRecord) => void | Promise<void> }) {
  const [name, setName] = useState(initial.name); const [description, setDescription] = useState(initial.description); const [price, setPrice] = useState(String(initial.basePrice)); const [duration, setDuration] = useState(initial.duration); const [inclusions, setInclusions] = useState(initial.inclusions); const [notes, setNotes] = useState(initial.notes); const [active, setActive] = useState(initial.active);
  return <div className="booking-overlay" role="dialog" aria-modal="true" aria-labelledby="package-edit-title"><form className="booking-drawer" onSubmit={(event) => { event.preventDefault(); if (!name.trim() || Number(price) < 0) return; void onSave({ ...initial, name: name.trim(), description: description.trim(), basePrice: Number(price), duration: duration.trim(), inclusions: inclusions.trim(), notes: notes.trim(), active }); }}><div className="drawer-header"><div><p className="eyebrow">Catalog editor</p><h2 id="package-edit-title">Edit package</h2></div><button className="close-button" type="button" onClick={onClose} aria-label="Close package editor"><X aria-hidden="true" /></button></div><div className="drawer-body"><div className="form-section"><div className="form-grid"><label className="wide-field">Package name<input value={name} onChange={(event) => setName(event.target.value)} required /></label><label className="wide-field">Description<input value={description} onChange={(event) => setDescription(event.target.value)} /></label><label>Base price<div className="money-input"><span>₱</span><input value={price} onChange={(event) => setPrice(event.target.value)} inputMode="decimal" required /></div></label><label>Estimated duration<input value={duration} onChange={(event) => setDuration(event.target.value)} /></label><label className="wide-field">Included services<textarea value={inclusions} onChange={(event) => setInclusions(event.target.value)} rows={3} /></label><label className="wide-field">Internal notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={3} /></label><label className="form-checkbox"><input type="checkbox" checked={active} onChange={(event) => setActive(event.target.checked)} /> Active package</label></div></div></div><div className="drawer-footer"><button className="secondary-button" type="button" onClick={onClose}>Cancel</button><button className="primary-button" type="submit">Save package</button></div></form></div>;
}
