"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { KeyRound, ShieldCheck } from "lucide-react";
import "../login/login.css";

export default function LoginPage(){const router=useRouter();const[bootstrap,setBootstrap]=useState(false);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[login,setLogin]=useState("");const[password,setPassword]=useState("");const[fullName,setFullName]=useState("");const[email,setEmail]=useState("");const[phone,setPhone]=useState("");const[facebookUrl,setFacebookUrl]=useState("");const[username,setUsername]=useState("");
useEffect(()=>{fetch("/api/auth/me",{cache:"no-store"}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error||"Database unavailable.");return x}).then(x=>{if(x.user)router.replace("/");else return fetch("/api/auth/bootstrap").then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||"Database unavailable.");return b}).then(b=>setBootstrap(Boolean(b.needsBootstrap)))}).catch(()=>setError("Local database is unavailable. Start PostgreSQL and retry.")).finally(()=>setLoading(false))},[router]);
useEffect(()=>{document.documentElement.dataset.theme=window.localStorage.getItem("salikha-theme")==="dark"?"dark":"light"},[]);
const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch(bootstrap?"/api/auth/bootstrap":"/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(bootstrap?{fullName,email,phone,facebookUrl,username,password}:{login,password})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Sign in failed.");router.replace("/");router.refresh()}catch(err){setError(err instanceof Error?err.message:"Sign in failed.")}finally{setBusy(false)}};
return <main className="login-page"><form className="login-card" onSubmit={submit}><div className="login-brand"><span>S</span><div><strong>Salikha</strong><small>Studio OS</small></div></div><div className="login-title-icon">{bootstrap?<ShieldCheck/>:<KeyRound/>}</div><p className="eyebrow">{bootstrap?"Secure workspace setup":"Welcome back"}</p><h1>{bootstrap?"Create the first admin":"Sign in"}</h1><p className="login-subtitle">{bootstrap?"This first account controls access and can add your team.":"Use your username or email and password."}</p>{loading?<p>Checking local account…</p>:<>
{bootstrap?<><label>Full name<input autoComplete="name" value={fullName} onChange={e=>setFullName(e.target.value)} required/></label><label>Email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Phone / GCash<input autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Facebook link<input type="url" value={facebookUrl} onChange={e=>setFacebookUrl(e.target.value)}/></label><label>Username<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required minLength={3}/></label></>:<label>Username or email<input autoComplete="username" value={login} onChange={e=>setLogin(e.target.value)} required/></label>}
<label>Password<input type="password" autoComplete={bootstrap?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)} required minLength={bootstrap?12:1}/>{bootstrap&&<small>Use at least 12 characters.</small>}</label>{error&&<p className="login-error" role="alert">{error}</p>}<button type="submit" disabled={loading||busy}>{busy?"Please wait…":bootstrap?"Create admin account":"Sign in securely"}</button></>}</form></main>}
