/**
 * AuditService.gs
 * Append-only audit logging to the AuditLogs sheet.
 *
 * Safety rules (docs/SECURITY_MODEL.md):
 * - Never stores secrets.
 * - Never logs full sensitive account references.
 * - Logs summaries rather than complete financial forms where possible.
 * - No deletion interface exists.
 */

var AuditService = (function () {
  'use strict';

  var SEVERITY_INFO = 'INFO';
  var SEVERITY_WARNING = 'WARNING';
  var SEVERITY_ERROR = 'ERROR';

  var ACTIONS = {
    DATABASE_INITIALIZED: 'DATABASE_INITIALIZED',
    ACCOUNT_CREATED: 'ACCOUNT_CREATED',
    ACCOUNT_UPDATED: 'ACCOUNT_UPDATED',
    ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
    CATEGORY_CREATED: 'CATEGORY_CREATED',
    CATEGORY_UPDATED: 'CATEGORY_UPDATED',
    CATEGORY_DEACTIVATED: 'CATEGORY_DEACTIVATED',
    OPENING_BALANCE_RECORDED: 'OPENING_BALANCE_RECORDED',
    TRANSACTION_POSTED: 'TRANSACTION_POSTED',
    TRANSACTION_VOIDED: 'TRANSACTION_VOIDED',
    TRANSFER_POSTED: 'TRANSFER_POSTED',
    TRANSFER_VOIDED: 'TRANSFER_VOIDED',
    DAILY_RECONCILIATION_SAVED: 'DAILY_RECONCILIATION_SAVED',
    BALANCE_VERIFICATION: 'BALANCE_VERIFICATION',
    DEVELOPMENT_RESET: 'DEVELOPMENT_RESET',
    CLIENT_CREATED: 'CLIENT_CREATED',
    CLIENT_UPDATED: 'CLIENT_UPDATED',
    CLIENT_ARCHIVED: 'CLIENT_ARCHIVED',
    CLIENT_REACTIVATED: 'CLIENT_REACTIVATED',
    CLIENT_DUPLICATE_OVERRIDE: 'CLIENT_DUPLICATE_OVERRIDE',
    CLIENT_NOTE_CREATED: 'CLIENT_NOTE_CREATED',
    CLIENT_NOTE_UPDATED: 'CLIENT_NOTE_UPDATED',
    CLIENT_INTERACTION_LOGGED: 'CLIENT_INTERACTION_LOGGED',
    LEAD_CREATED: 'LEAD_CREATED',
    LEAD_UPDATED: 'LEAD_UPDATED',
    LEAD_STATUS_CHANGED: 'LEAD_STATUS_CHANGED',
    LEAD_ARCHIVED: 'LEAD_ARCHIVED',
    LEAD_REACTIVATED: 'LEAD_REACTIVATED',
    LEAD_CONVERTED: 'LEAD_CONVERTED',
    PACKAGE_CREATED: 'PACKAGE_CREATED',
    PACKAGE_UPDATED: 'PACKAGE_UPDATED',
    PACKAGE_DEACTIVATED: 'PACKAGE_DEACTIVATED',
    PACKAGE_REACTIVATED: 'PACKAGE_REACTIVATED',
    PACKAGE_ITEMS_UPDATED: 'PACKAGE_ITEMS_UPDATED',
    ADD_ON_CREATED: 'ADD_ON_CREATED',
    ADD_ON_UPDATED: 'ADD_ON_UPDATED',
    ADD_ON_DEACTIVATED: 'ADD_ON_DEACTIVATED',
    BOOKING_CREATED: 'BOOKING_CREATED',
    BOOKING_UPDATED: 'BOOKING_UPDATED',
    BOOKING_STATUS_CHANGED: 'BOOKING_STATUS_CHANGED',
    BOOKING_CANCELLED: 'BOOKING_CANCELLED',
    BOOKING_ARCHIVED: 'BOOKING_ARCHIVED',
    BOOKING_REACTIVATED: 'BOOKING_REACTIVATED',
    BOOKING_RESCHEDULED: 'BOOKING_RESCHEDULED',
    BOOKING_CONFLICT_OVERRIDE: 'BOOKING_CONFLICT_OVERRIDE',
    BOOKING_PRICING_UPDATED: 'BOOKING_PRICING_UPDATED',
    PAYMENT_RECORDED: 'PAYMENT_RECORDED',
    PAYMENT_VOIDED: 'PAYMENT_VOIDED',
    PAYMENT_OVERPAYMENT_OVERRIDE: 'PAYMENT_OVERPAYMENT_OVERRIDE',
    REFUND_RECORDED: 'REFUND_RECORDED',
    REFUND_VOIDED: 'REFUND_VOIDED',
    RECEIVABLE_RECALCULATED: 'RECEIVABLE_RECALCULATED',
    BOOKING_BALANCE_REPAIRED: 'BOOKING_BALANCE_REPAIRED',
    EXPENSE_CREATED: 'EXPENSE_CREATED',
    EXPENSE_UPDATED: 'EXPENSE_UPDATED',
    EXPENSE_SUBMITTED: 'EXPENSE_SUBMITTED',
    EXPENSE_APPROVED: 'EXPENSE_APPROVED',
    EXPENSE_REJECTED: 'EXPENSE_REJECTED',
    EXPENSE_PAID: 'EXPENSE_PAID',
    EXPENSE_VOIDED: 'EXPENSE_VOIDED',
    BOOKING_COSTS_RECALCULATED: 'BOOKING_COSTS_RECALCULATED',
    OPERATING_ALLOCATION_RECALCULATED: 'OPERATING_ALLOCATION_RECALCULATED',
    INVENTORY_ITEM_CREATED: 'INVENTORY_ITEM_CREATED',
    INVENTORY_ITEM_UPDATED: 'INVENTORY_ITEM_UPDATED',
    INVENTORY_ITEM_DEACTIVATED: 'INVENTORY_ITEM_DEACTIVATED',
    INVENTORY_ITEM_REACTIVATED: 'INVENTORY_ITEM_REACTIVATED',
    STOCK_IN_RECORDED: 'STOCK_IN_RECORDED',
    OPENING_STOCK_RECORDED: 'OPENING_STOCK_RECORDED',
    STOCK_ADJUSTMENT_RECORDED: 'STOCK_ADJUSTMENT_RECORDED',
    STOCK_WRITE_OFF_RECORDED: 'STOCK_WRITE_OFF_RECORDED',
    STOCK_USAGE_RECORDED: 'STOCK_USAGE_RECORDED',
    STOCK_RETURN_RECORDED: 'STOCK_RETURN_RECORDED',
    SUPPLIER_CREATED: 'SUPPLIER_CREATED',
    SUPPLIER_UPDATED: 'SUPPLIER_UPDATED',
    SUPPLIER_DEACTIVATED: 'SUPPLIER_DEACTIVATED',
    SUPPLIER_REACTIVATED: 'SUPPLIER_REACTIVATED',
    PURCHASE_CREATED: 'PURCHASE_CREATED',
    PURCHASE_UPDATED: 'PURCHASE_UPDATED',
    PURCHASE_ORDERED: 'PURCHASE_ORDERED',
    PURCHASE_RECEIVED: 'PURCHASE_RECEIVED',
    PURCHASE_CANCELLED: 'PURCHASE_CANCELLED',
    EQUIPMENT_CREATED: 'EQUIPMENT_CREATED',
    EQUIPMENT_UPDATED: 'EQUIPMENT_UPDATED',
    EQUIPMENT_STATUS_CHANGED: 'EQUIPMENT_STATUS_CHANGED',
    EQUIPMENT_MOVEMENT_RECORDED: 'EQUIPMENT_MOVEMENT_RECORDED',
    TASK_CREATED: 'TASK_CREATED',
    TASK_UPDATED: 'TASK_UPDATED',
    TASK_COMPLETED: 'TASK_COMPLETED',
    TASK_REOPENED: 'TASK_REOPENED',
    TASK_CANCELLED: 'TASK_CANCELLED',
    PRODUCTION_PLANNED: 'PRODUCTION_PLANNED',
    PRODUCTION_MARKED_READY: 'PRODUCTION_MARKED_READY',
    DEPLOYMENT_CREATED: 'DEPLOYMENT_CREATED',
    DEPLOYMENT_LOADING: 'DEPLOYMENT_LOADING',
    DEPLOYMENT_DEPARTED: 'DEPLOYMENT_DEPARTED',
    DEPLOYMENT_RETURNED: 'DEPLOYMENT_RETURNED',
    DEPLOYMENT_RECONCILED: 'DEPLOYMENT_RECONCILED',
    DEPLOYMENT_CLOSED: 'DEPLOYMENT_CLOSED',
    DEPLOYMENT_ITEM_ADDED: 'DEPLOYMENT_ITEM_ADDED',
    DEPLOYMENT_ITEM_UPDATED: 'DEPLOYMENT_ITEM_UPDATED',
    DEPLOYMENT_EQUIPMENT_ADDED: 'DEPLOYMENT_EQUIPMENT_ADDED',
    DEPLOYMENT_CHECKLIST_ITEM_DONE: 'DEPLOYMENT_CHECKLIST_ITEM_DONE',
    DEPLOYMENT_CHECKLIST_ITEM_ADDED: 'DEPLOYMENT_CHECKLIST_ITEM_ADDED',
    DEPLOYMENT_INCIDENT_LOGGED: 'DEPLOYMENT_INCIDENT_LOGGED',
    DEPLOYMENT_INCIDENT_RESOLVED: 'DEPLOYMENT_INCIDENT_RESOLVED',
    CREW_MEMBER_CREATED: 'CREW_MEMBER_CREATED',
    CREW_MEMBER_UPDATED: 'CREW_MEMBER_UPDATED',
    CREW_MEMBER_DEACTIVATED: 'CREW_MEMBER_DEACTIVATED',
    CREW_MEMBER_REACTIVATED: 'CREW_MEMBER_REACTIVATED',
    CREW_ASSIGNMENT_CREATED: 'CREW_ASSIGNMENT_CREATED',
    CREW_ASSIGNMENT_UPDATED: 'CREW_ASSIGNMENT_UPDATED',
    CREW_ASSIGNMENT_SIGNED_OFF: 'CREW_ASSIGNMENT_SIGNED_OFF',
    CREW_PAYMENT_RECORDED: 'CREW_PAYMENT_RECORDED',
    CREW_PAYMENT_VOIDED: 'CREW_PAYMENT_VOIDED',
    PARTNER_CREATED: 'PARTNER_CREATED',
    PARTNER_UPDATED: 'PARTNER_UPDATED',
    PARTNER_DEACTIVATED: 'PARTNER_DEACTIVATED',
    PARTNER_REACTIVATED: 'PARTNER_REACTIVATED',
    COMMISSION_CREATED: 'COMMISSION_CREATED',
    COMMISSION_DUE: 'COMMISSION_DUE',
    COMMISSION_PAID: 'COMMISSION_PAID',
    COMMISSION_VOIDED: 'COMMISSION_VOIDED',
    REPORT_EXPORTED: 'REPORT_EXPORTED',
    AUTOMATION_SETTINGS_CHANGED: 'AUTOMATION_SETTINGS_CHANGED',
    AUTOMATION_TRIGGERS_SETUP: 'AUTOMATION_TRIGGERS_SETUP',
    AUTOMATION_TRIGGERS_REMOVED: 'AUTOMATION_TRIGGERS_REMOVED',
    BACKUP_STARTED: 'BACKUP_STARTED',
    BACKUP_COMPLETED: 'BACKUP_COMPLETED',
    BACKUP_FAILED: 'BACKUP_FAILED',
    BACKUP_VERIFICATION: 'BACKUP_VERIFICATION',
    BACKUP_RESTORE_TEST: 'BACKUP_RESTORE_TEST',
    CALENDAR_SYNCED: 'CALENDAR_SYNCED',
    CALENDAR_EVENT_UPDATED: 'CALENDAR_EVENT_UPDATED',
    CALENDAR_EVENT_CANCELLED: 'CALENDAR_EVENT_CANCELLED',
    CALENDAR_SYNC_FAILED: 'CALENDAR_SYNC_FAILED',
    DIGEST_SENT: 'DIGEST_SENT',
    DIGEST_FAILED: 'DIGEST_FAILED',
    LOW_STOCK_ALERT_SENT: 'LOW_STOCK_ALERT_SENT',
    FILE_UPLOADED: 'FILE_UPLOADED',
    FILE_TRASHED: 'FILE_TRASHED',
    SYSTEM_SETUP_STARTED: 'SYSTEM_SETUP_STARTED',
    SYSTEM_SETUP_COMPLETED: 'SYSTEM_SETUP_COMPLETED',
    SYSTEM_SETUP_FAILED: 'SYSTEM_SETUP_FAILED',
    SYSTEM_SETUP_STEP: 'SYSTEM_SETUP_STEP',
    SYSTEM_SETUP_SECURITY: 'SYSTEM_SETUP_SECURITY'
  };

  /**
   * Resolves the temporary actor context.
   * Full authentication lands in a future sprint; see docs/SECURITY_MODEL.md.
   *
   * Test seam: the in-memory harness can call _setTestActor({role,userId,name})
   * to inject a role-bearing actor (used by Sprint 5/9 Purchasing and other
   * permission tests); the setter has no effect in the deployed web app
   * because Session-based resolution happens first in production and the
   * harness never calls this seam. Cleared by _clearTestActor.
   */
  function getActor() {
    if (typeof testActor !== 'undefined' && testActor) {
      return testActor;
    }
    var userId = 'unknown-user';
    var name = 'Unknown User';
    try {
      var email = Session.getActiveUser().getEmail();
      if (email) {
        userId = email;
        name = email;
      }
    } catch (ignored) {
      /* email is not always available; fall back to a documented actor */
    }
    return { userId: userId, name: name };
  }

  var testActor = null;
  function _setTestActor(actor) {
    testActor = actor || null;
  }
  function _clearTestActor() {
    testActor = null;
  }

  function safeJson(value) {
    if (value === undefined || value === null) {
      return '';
    }
    try {
      var text = JSON.stringify(value);
      return text && text.length > 2000 ? text.substring(0, 2000) : text;
    } catch (e) {
      return '';
    }
  }

  /**
   * Writes an audit entry. Never throws to the caller unless the sheet
   * itself is broken.
   */
  function write(entry) {
    var actor = entry.actor || getActor();
    var record = {
      audit_id: entry.auditId || IdService.generateId('AUD'),
      timestamp: DateService.nowIso(),
      actor_id: entry.actorId || actor.userId,
      actor_name: entry.actorName || actor.name,
      action: entry.action,
      entity_type: entry.entityType || '',
      entity_id: entry.entityId || '',
      summary: entry.summary || '',
      before_data: safeJson(entry.beforeData),
      after_data: safeJson(entry.afterData),
      metadata: safeJson(entry.metadata),
      severity: entry.severity || SEVERITY_INFO,
      request_id: entry.requestId || ''
    };
    try {
      RepositoryService.appendRecord(SheetSchemaService.SHEET_AUDIT_LOGS, record);
    } catch (e) {
      LoggerService.error('AuditService.write', 'Failed to write audit entry', {
        action: entry.action
      });
    }
  }

  function info(action, entityType, entityId, summary, opts) {
    opts = opts || {};
    write({
      action: action,
      entityType: entityType,
      entityId: entityId,
      summary: summary,
      beforeData: opts.beforeData,
      afterData: opts.afterData,
      metadata: opts.metadata,
      severity: SEVERITY_INFO
    });
  }

  function warn(action, entityType, entityId, summary, opts) {
    opts = opts || {};
    write({
      action: action,
      entityType: entityType,
      entityId: entityId,
      summary: summary,
      beforeData: opts.beforeData,
      afterData: opts.afterData,
      metadata: opts.metadata,
      severity: SEVERITY_WARNING
    });
  }

  return {
    write: write,
    info: info,
    warn: warn,
    getActor: getActor,
    _setTestActor: _setTestActor,
    _clearTestActor: _clearTestActor,
    ACTIONS: ACTIONS,
    SEVERITY_INFO: SEVERITY_INFO,
    SEVERITY_WARNING: SEVERITY_WARNING,
    SEVERITY_ERROR: SEVERITY_ERROR
  };
})();
